#!/usr/bin/env bash
# This script changes localhost to 127.0.0.2 and sets facebook.com to 8.8.8.8

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Update localhost resolve IP
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

# Force facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
