#!/usr/bin/env bash

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Replace localhost -> 127.0.0.2
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts

# Add facebook.com -> 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts

