#!/usr/bin/env bash
# This script sets localhost IP to 127.0.0.2 and facebook.com to 8.8.8.8

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Rewrite hosts file
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
    grep -v "localhost" /etc/hosts.bak | grep -v "facebook.com"
} > /etc/hosts

